"""
Graph RAG Extraction for Malta Laws
Fresh implementation with proper ID structure for Graph RAG

ID Structure:
- Articles (Cap.): art:Cap.9/5
- Regulations (S.L.): reg:S.L.146.02/5
- Schedules: sched:S.L.199.01/Schedule
- Schedule Regulations: sched:S.L.455.13/Schedule/Reg1
- Tables: sched:S.L.499.18/Schedule/Table

Chunking:
- Articles/Regulations: Whole with all sub-articles (preserves meaning)
- Schedules: Whole schedule OR per regulation if schedule contains regulations
- Tables: Whole table with AI-generated description
"""

import fitz  # PyMuPDF
import base64
import json
import os
import sys
import io
import time
import re
import signal
from pathlib import Path
from typing import List, Dict, Optional, Tuple, Any
from dataclasses import dataclass, asdict
from datetime import datetime
from func_timeout import func_timeout, FunctionTimedOut

# Vertex AI imports
import vertexai
from vertexai.generative_models import GenerativeModel, Part, SafetySetting, HarmCategory

# Fix encoding for Windows
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

# =============================================================================
# LOAD .ENV FILE
# =============================================================================

def load_env():
    """Load environment variables from .env file."""
    env_path = Path(__file__).parent / '.env'
    if env_path.exists():
        with open(env_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    os.environ[key.strip()] = value.strip()

    # Set absolute path for credentials
    creds = os.environ.get('GOOGLE_APPLICATION_CREDENTIALS', '')
    if creds and not Path(creds).is_absolute():
        os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = str(Path(__file__).parent / creds)

load_env()

# =============================================================================
# CONFIGURATION
# =============================================================================

# Load laws to extract from JSON file (generated by generate_extraction_list.py)
LAWS_EXTRACTION_FILE = "laws_to_extract.json"

def load_laws_to_extract():
    """Load the list of laws to extract from JSON file."""
    if Path(LAWS_EXTRACTION_FILE).exists():
        with open(LAWS_EXTRACTION_FILE, 'r', encoding='utf-8') as f:
            return json.load(f)
    else:
        # Fallback to single law for testing
        print(f"Warning: {LAWS_EXTRACTION_FILE} not found. Using fallback single law.")
        return [
            {
                "pdf_path": "All Malta law PDFs/Companies Act (Forms) Regulations (S.L. 386.01).pdf",
                "cap": "S.L. 386.01",
                "name": "Companies Act (Forms) Regulations",
                "page_range": None
            }
        ]

LAWS_TO_EXTRACT = load_laws_to_extract()

# Vertex AI settings from .env
PROJECT_ID = os.environ.get('GOOGLE_CLOUD_PROJECT', '')
LOCATION = os.environ.get('VERTEX_AI_LOCATION', 'us-central1')

# Model hierarchy for fallback
MODELS = {
    "primary": "gemini-2.5-flash",
    "fallback_1": "gemini-2.5-pro"
}

# Retry settings
MAX_RETRIES = 2
RETRY_DELAY = 2  # seconds
API_TIMEOUT = 300  # seconds - timeout for API calls to prevent hanging (5 minutes - increased for complex pages)

# Output directory for extraction files
OUTPUT_DIR = "extractions"

# Summary cache (shared with multi_model_extraction.py)
SUMMARIES_CACHE_PATH = "law_summaries.json"

# Global state for interrupt handling
_extraction_in_progress = None
_all_completed_extractions = []

# Safety settings (lenient for legal content)
SAFETY_SETTINGS = [
    SafetySetting(
        category=HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
        threshold=SafetySetting.HarmBlockThreshold.BLOCK_ONLY_HIGH
    ),
    SafetySetting(
        category=HarmCategory.HARM_CATEGORY_HATE_SPEECH,
        threshold=SafetySetting.HarmBlockThreshold.BLOCK_ONLY_HIGH
    ),
    SafetySetting(
        category=HarmCategory.HARM_CATEGORY_HARASSMENT,
        threshold=SafetySetting.HarmBlockThreshold.BLOCK_ONLY_HIGH
    ),
    SafetySetting(
        category=HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT,
        threshold=SafetySetting.HarmBlockThreshold.BLOCK_ONLY_HIGH
    ),
]

# =============================================================================
# TIMEOUT WRAPPER FOR API CALLS
# =============================================================================

def generate_content_with_timeout(model: GenerativeModel, *args, **kwargs):
    """
    Wrapper for model.generate_content with timeout protection.
    Uses func_timeout to prevent API calls from hanging indefinitely.

    Args:
        model: The GenerativeModel instance
        *args: Positional arguments for generate_content
        **kwargs: Keyword arguments for generate_content

    Returns:
        Response from generate_content

    Raises:
        FunctionTimedOut: If the call exceeds API_TIMEOUT seconds
    """
    return func_timeout(API_TIMEOUT, model.generate_content, args=args, kwargs=kwargs)


# =============================================================================
# CACHE FUNCTIONS (shared with multi_model_extraction.py)
# =============================================================================

def load_summaries_cache() -> Dict:
    """Load cached law summaries from JSON file."""
    if Path(SUMMARIES_CACHE_PATH).exists():
        with open(SUMMARIES_CACHE_PATH, 'r', encoding='utf-8') as f:
            return json.load(f)
    return {}


def save_summaries_cache(summaries: Dict):
    """Save law summaries to JSON cache file."""
    with open(SUMMARIES_CACHE_PATH, 'w', encoding='utf-8') as f:
        json.dump(summaries, f, indent=2, ensure_ascii=False)


def get_parent_code(sl_code: str) -> Optional[str]:
    """
    Extract parent Cap number from S.L. code.
    S.L. 9.01 -> Cap. 9
    S.L. 441.04 -> Cap. 441
    """
    if not sl_code or not sl_code.startswith("S.L."):
        return None
    parts = sl_code.replace("S.L.", "").strip().split(".")
    if parts:
        parent_num = parts[0].strip()
        return f"Cap. {parent_num}"
    return None


# =============================================================================
# DATA STRUCTURES
# =============================================================================

@dataclass
class ExtractionResult:
    """Result from extracting a single page"""
    page_num: int
    content_type: str  # "article", "regulation", "schedule", "schedule_regulation", "table", "skip"
    items: List[Dict]
    skip_reason: Optional[str] = None
    raw_response: Optional[str] = None


@dataclass
class LawMetadata:
    """Metadata for a law - used for RAG filtering and search.
    Matches structure in law_summaries.json for consistency with multi_model_extraction.
    """
    purpose: str  # What this law is about
    key_topics: List[str]  # 5-10 specific topics/subjects
    scope: str  # Who/what does this law apply to
    categories: List[str]  # snake_case: criminal_law, civil_law, etc.
    summary_text: str  # Concise summary for search purposes
    relation_to_parent: Optional[str] = None  # For S.L. laws: how it implements parent law
    status: str = "success"  # "success" or "error"


@dataclass
class LawExtraction:
    """Complete extraction for one law"""
    law_code: str
    law_name: str
    law_type: str  # "chapter" or "subsidiary"
    content_key: str  # "articles" or "regulations"
    metadata: Optional[LawMetadata]  # Category, summary, keywords for RAG
    items: List[Dict]  # articles or regulations
    schedules: List[Dict]
    miscellaneous: List[Dict]  # Fallback extracted content
    skipped: List[Dict]
    metrics: Dict
    edges: List[Dict]  # Graph edges for cross-references


# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

def is_subsidiary_legislation(cap: str) -> bool:
    """Check if this is subsidiary legislation (S.L.) vs main chapter (Cap.)"""
    return cap.strip().upper().startswith("S.L.")


def get_content_type_name(cap: str) -> str:
    """Get the name for content items (articles vs regulations)"""
    return "regulations" if is_subsidiary_legislation(cap) else "articles"


def get_item_type(cap: str) -> str:
    """Get the type for individual items"""
    return "regulation" if is_subsidiary_legislation(cap) else "article"


def get_id_prefix(cap: str) -> str:
    """Get ID prefix based on law type"""
    return "reg" if is_subsidiary_legislation(cap) else "art"


def normalize_code(cap: str) -> str:
    """Normalize law code for ID generation (remove spaces)"""
    return cap.replace(" ", "")


def generate_item_id(cap: str, number: str) -> str:
    """Generate unique ID for article/regulation

    Examples:
        art:Cap.9/5
        reg:S.L.146.02/5
    """
    prefix = get_id_prefix(cap)
    code = normalize_code(cap)
    # Clean the number (remove any leading zeros, spaces)
    clean_num = number.strip()
    return f"{prefix}:{code}/{clean_num}"


def generate_schedule_id(cap: str, schedule_name: Optional[str] = None, regulation_num: Optional[str] = None) -> str:
    """Generate unique ID for schedule or schedule regulation

    Examples:
        sched:S.L.199.01/Schedule
        sched:S.L.199.01/FirstSchedule
        sched:S.L.455.13/Schedule/Reg1
    """
    code = normalize_code(cap)

    # Handle None or empty schedule name
    if not schedule_name:
        clean_name = "Schedule"
    else:
        # Clean schedule name
        clean_name = schedule_name.replace(" ", "").replace("SCHEDULE", "Schedule")
        if not clean_name or clean_name.lower() == "schedule":
            clean_name = "Schedule"

    if regulation_num:
        return f"sched:{code}/{clean_name}/Reg{regulation_num}"
    return f"sched:{code}/{clean_name}"


def extract_main_number(number: str) -> str:
    """Extract main article/regulation number from full number

    Examples:
        "5" -> "5"
        "5(1)" -> "5"
        "5(2)(a)" -> "5"
        "23A" -> "23A"
        "23A(1)" -> "23A"
        "article 492" -> "492"
        "articles 204A" -> "204A"
    """
    # First, strip common prefixes
    cleaned = clean_reference_target(number)
    # Match the main number (digits optionally followed by letter)
    match = re.match(r'^(\d+[A-Za-z]?)', cleaned.strip())
    if match:
        return match.group(1)
    return cleaned.strip()


def clean_reference_target(target: str) -> str:
    """Clean reference target by removing 'article', 'articles', 'regulation', etc.

    Examples:
        "article 492" -> "492"
        "articles 204A" -> "204A"
        "regulation 5" -> "5"
        "5(1)" -> "5(1)"
    """
    if not target:
        return target
    # Remove common prefixes (case-insensitive)
    cleaned = re.sub(r'^(articles?|regulations?|sub-?articles?|sub-?regulations?)\s*', '', target.strip(), flags=re.IGNORECASE)
    return cleaned.strip()


def expand_reference_range(range_str: str) -> List[str]:
    """Expand a range reference like '311 to 318' into individual numbers.

    Examples:
        "311 to 318" -> ["311", "312", "313", "314", "315", "316", "317", "318"]
        "5 to 7" -> ["5", "6", "7"]
        "204A to 204C" -> ["204A", "204B", "204C"]  (letter ranges)
        "5" -> ["5"]  (no range, returns single item)
    """
    range_str = clean_reference_target(range_str)

    # Check for range pattern: "X to Y" or "X-Y"
    range_match = re.match(r'^(\d+[A-Za-z]?)\s*(?:to|-)\s*(\d+[A-Za-z]?)$', range_str.strip(), re.IGNORECASE)

    if not range_match:
        # No range, return single item
        return [range_str.strip()] if range_str.strip() else []

    start_str, end_str = range_match.groups()

    # Check if both are pure numbers
    start_num_match = re.match(r'^(\d+)([A-Za-z]?)$', start_str)
    end_num_match = re.match(r'^(\d+)([A-Za-z]?)$', end_str)

    if not start_num_match or not end_num_match:
        return [start_str, end_str]

    start_num, start_letter = int(start_num_match.group(1)), start_num_match.group(2)
    end_num, end_letter = int(end_num_match.group(1)), end_num_match.group(2)

    result = []

    # If both have same letter suffix or no letter
    if start_letter == end_letter:
        for n in range(start_num, end_num + 1):
            result.append(f"{n}{start_letter}")
    # If letters differ but numbers same (e.g., 204A to 204C)
    elif start_num == end_num and start_letter and end_letter:
        for letter in range(ord(start_letter.upper()), ord(end_letter.upper()) + 1):
            result.append(f"{start_num}{chr(letter)}")
    # Otherwise, just do numeric range (ignore letters)
    else:
        for n in range(start_num, end_num + 1):
            result.append(str(n))

    return result if result else [range_str]


def parse_external_reference(ref_text: str, target_law: str) -> Dict:
    """Parse an external reference and determine the appropriate ID structure.

    Returns:
        Dict with 'target_id' and 'has_article'

    Examples:
        ("article 7", "Cap. 16") -> {"target_id": "art:Cap.16/7", "has_article": True}
        ("Immigration Act", None) -> {"target_id": "law:ImmigrationAct", "has_article": False}
        ("", "Cap. 16") -> {"target_id": "law:Cap.16", "has_article": False}
    """
    if not target_law:
        return {"target_id": None, "has_article": False}

    target_code = normalize_code(target_law)
    cleaned_ref = clean_reference_target(ref_text) if ref_text else ""

    # Check if we have a specific article/regulation number
    num_match = re.match(r'^(\d+[A-Za-z]?)(?:\(|$)', cleaned_ref)

    if num_match:
        # We have a specific article number
        article_num = num_match.group(1)
        prefix = "reg" if is_subsidiary_legislation(target_law) else "art"
        return {
            "target_id": f"{prefix}:{target_code}/{article_num}",
            "has_article": True
        }
    else:
        # Just the law reference, no specific article
        return {
            "target_id": f"law:{target_code}",
            "has_article": False
        }


def page_to_image_base64(page: fitz.Page, dpi: int = 150) -> str:
    """Convert PDF page to base64 encoded PNG"""
    mat = fitz.Matrix(dpi / 72, dpi / 72)
    pix = page.get_pixmap(matrix=mat)
    img_bytes = pix.tobytes("png")
    return base64.b64encode(img_bytes).decode('utf-8')


# =============================================================================
# PROMPTS
# =============================================================================

def build_extraction_prompt(
    cap: str,
    law_name: str,
    is_subsidiary: bool,
    prev_item_number: Optional[str] = None,
    prev_item_ended: bool = True,
    prev_schedule_section: Optional[str] = None,
    prev_schedule_ended: bool = True,
    prev_form_number: Optional[str] = None,
    prev_form_ended: bool = True
) -> str:
    """Build the comprehensive extraction prompt with PTCF framework and few-shot examples.

    Adapted from multi_model_extraction.py with article vs regulation distinction.
    """

    # Determine terminology based on law type
    item_type = "regulation" if is_subsidiary else "article"
    item_type_upper = item_type.upper()
    item_type_plural = "regulations" if is_subsidiary else "articles"

    # Get main item number from previous
    main_item = None
    if prev_item_number:
        match = re.match(r'^(\d+[A-Za-z]?)', prev_item_number)
        if match:
            main_item = match.group(1)

    # Build previous page context
    if prev_item_number and not prev_item_ended:
        prev_context = f"""
=== PREVIOUS PAGE CONTEXT ===
The PREVIOUS page ended with {item_type} {prev_item_number} which DID NOT END.
Any text at the TOP of this page belongs to {item_type} {prev_item_number}.
The main {item_type} is {main_item} - any sub-{item_type}s like (1A), (2), (3) on this page belong to {item_type} {main_item}.
"""
    elif prev_item_number:
        prev_context = f"""
=== PREVIOUS PAGE CONTEXT ===
The PREVIOUS page ended with {item_type} {prev_item_number}.
The main {item_type} was {main_item}. If this page continues with sub-{item_type}s like (1A), (2), (3), (a), (b) etc.
that belong to the same main {item_type}, prefix them with {main_item} (e.g., {main_item}(1A), {main_item}(2)).
Look for a NEW main {item_type} (bold number with period like "29." or "30.") to know when {main_item} ends.
"""
    else:
        prev_context = """
=== PREVIOUS PAGE CONTEXT ===
This is the first page being analyzed.
"""

    # Schedule context
    if prev_schedule_section:
        if not prev_schedule_ended:
            prev_context += f"""
=== PREVIOUS SCHEDULE CONTEXT ===
The PREVIOUS page ended with schedule section {prev_schedule_section} which DID NOT END.
Any text at the TOP of this page that continues the schedule content belongs to {prev_schedule_section}.
Set "schedule_continues_from_previous": true for the first schedule item.
"""
        else:
            prev_context += f"""
=== PREVIOUS SCHEDULE CONTEXT ===
The PREVIOUS page had schedule section {prev_schedule_section}.
If this page continues with schedule content, check if it's a new section or continuation.
"""

    # Form context
    if prev_form_number:
        if not prev_form_ended:
            prev_context += f"""
=== PREVIOUS FORM CONTEXT ===
The PREVIOUS page ended with {prev_form_number} which DID NOT END (form continues to next page).
This page is a CONTINUATION of {prev_form_number}.
Set "page_content_type": "form" and "form_continues_from_previous": true.
"""

    # Law type info
    law_type_info = "SUBSIDIARY LEGISLATION (S.L.)" if is_subsidiary else "CHAPTER (Cap.) - Main Law"

    return f"""You are analyzing a page from the Maltese {law_name} ({cap}).
{prev_context}

=== DOCUMENT TYPE ===
{law_type_info}
In {"subsidiary legislation" if is_subsidiary else "chapters"}, bold numbers with periods are called {item_type_upper}S.

=== DOCUMENT LAYOUT ===

This legal document has two columns:
- MAIN TEXT (left/center): Legal provisions with {item_type} numbers in bold followed by period (1., 2., 23B., etc.)
- RIGHT MARGIN (narrow): Amendment history and Cap. numbers - ignore this in {item_type} text

=== STEP 1: IDENTIFY PAGE CONTENT TYPE ===

CRITICAL: Identify the page type FIRST before attempting extraction.

**If this page is a FORM** (blank application form with empty fields like "Name: _____", "Date: _____"):
- Set "page_content_type" to "form"
- Set "{item_type_plural}" to []
- Set "schedule_content" to []
- **CRITICAL - FORM NUMBER DETECTION**: Look for form markers - BOTH numeric AND letter forms:
  - Numeric: "Form 1", "Form 2", "Form 3", etc.
  - **Letter-based**: "Form A", "Form B", "Form BB", "Form I", "Form J", "Form KK", etc.
  - Set "last_form_number" to the form identifier found
- Return immediately - DO NOT try to extract structured content from blank forms

**Otherwise**, determine content type by following this EXACT decision tree:

<persona>You are a legal document classifier for Maltese law extraction.</persona>

<task>Classify this page from {law_name} ({cap}) and extract structured content.</task>

<examples>

Example 1 - SCHEDULE PAGE:
INPUT: Page header contains "PART II", "FIRST SCHEDULE", "PART II - FEES"
Content shows:
"1. For the registration of an act of birth € 2.60
 2. For the registration of an act of marriage or a civil union € 2.60
 3. For every certificate attesting that no entry exists in Civil Status Records..."

CLASSIFICATION DECISION:
- Keywords found: "FIRST SCHEDULE" + "PART II" + "FEES" → SCHEDULE PAGE
- Numbered items (1., 2., 3.) with fee amounts → schedule_text type
- Must extract to schedule_content array, NOT {item_type_plural} array

OUTPUT:
{{
  "page_content_type": "schedule_text",
  "schedule_name": "FIRST SCHEDULE",
  "{item_type_plural}": [],
  "schedule_content": [
    {{"number": "1", "text": "For the registration of an act of birth € 2.60", "continues_from_previous": false, "continues_to_next": false}},
    {{"number": "2", "text": "For the registration of an act of marriage or a civil union € 2.60", "continues_from_previous": false, "continues_to_next": false}}
  ],
  "last_{item_type}_on_page": null,
  "last_schedule_section": "2",
  "cross_references": []
}}

Example 2 - FORM TEMPLATE PAGE:
INPUT: Page header contains "FORM A", "({item_type_upper} 190)", "EDICT FOR INFORMATION"
Content shows legal notice template text with blanks: "Whereas _____ has, by an application filed on the _____"

CLASSIFICATION DECISION:
- Keyword found: "FORM A" → FORM PAGE
- Contains text description with blanks → form_template type
- Must set {item_type_plural} = [] and schedule_content = []

OUTPUT:
{{
  "page_content_type": "form_template",
  "schedule_name": null,
  "{item_type_plural}": [],
  "schedule_content": [],
  "last_{item_type}_on_page": null,
  "last_form_number": "Form A",
  "last_form_ended": true,
  "cross_references": []
}}

Example 3 - {item_type_upper}S PAGE WITH HIERARCHY:
INPUT: Page shows {item_type} with nested sub-sections:
"4. Board Composition
     (1) The board shall consist of qualified members.
     (2) Members shall include:
         (a) a chairperson
         (b) a deputy chairperson
     (3) Disqualifications:
         (a) convicted persons
         (b) interdicted persons
         (c) judges and magistrates"

CLASSIFICATION DECISION:
- No "SCHEDULE" or "FORM" keywords → {item_type_upper}S PAGE
- Must track hierarchy: (a) and (b) under (2) are "4(2)(a)", "4(2)(b)"
- Must track hierarchy: (a), (b), (c) under (3) are "4(3)(a)", "4(3)(b)", "4(3)(c)"

OUTPUT:
{{
  "page_content_type": "{item_type_plural}",
  "schedule_name": null,
  "{item_type_plural}": [
    {{
      "number": "4",
      "title": "Board Composition",
      "text": "(1) The board shall consist of qualified members.\\n(2) Members shall include:\\n(a) a chairperson\\n(b) a deputy chairperson\\n(3) Disqualifications:\\n(a) convicted persons\\n(b) interdicted persons\\n(c) judges and magistrates",
      "sub_items": ["4(1)", "4(2)", "4(2)(a)", "4(2)(b)", "4(3)", "4(3)(a)", "4(3)(b)", "4(3)(c)"],
      "continues_from_previous": false,
      "continues_to_next": false
    }}
  ],
  "schedule_content": [],
  "last_{item_type}_on_page": "4",
  "last_{item_type}_ended": true,
  "cross_references": []
}}

Example 4 - SIMPLE {item_type_upper}S PAGE:
INPUT: Page shows simple numbered {item_type_plural}:
"5. (1) Every person who commits an offence...
      (2) The court may impose penalties...
 6. The Minister may make regulations..."

OUTPUT:
{{
  "page_content_type": "{item_type_plural}",
  "schedule_name": null,
  "{item_type_plural}": [
    {{"number": "5", "title": "Offences", "text": "(1) Every person who commits an offence...\\n(2) The court may impose penalties...", "sub_items": ["5(1)", "5(2)"], "continues_from_previous": false, "continues_to_next": false}},
    {{"number": "6", "title": "Regulations", "text": "The Minister may make regulations...", "sub_items": [], "continues_from_previous": false, "continues_to_next": false}}
  ],
  "schedule_content": [],
  "last_{item_type}_on_page": "6",
  "last_{item_type}_ended": true,
  "cross_references": []
}}

Example 5 - SCHEDULE WITH REGULATIONS:
INPUT: Page inside a schedule shows "REGULATION 1 - APPLICABILITY", "REGULATION 2 - VIOLATIONS"
These are NOT regular {item_type_plural}, they are regulations WITHIN the schedule.

OUTPUT:
{{
  "page_content_type": "schedule_regulations",
  "schedule_name": "SCHEDULE",
  "{item_type_plural}": [],
  "schedule_content": [],
  "schedule_regulations": [
    {{"regulation_number": "1", "title": "APPLICABILITY", "text": "These regulations shall apply to..."}},
    {{"regulation_number": "2", "title": "VIOLATIONS", "text": "The following constitute violations..."}}
  ],
  "last_{item_type}_on_page": null,
  "cross_references": []
}}

</examples>

<classification_instructions>

Follow this decision tree for EVERY page:

STEP 1: Scan TOP 20% of page for SCHEDULE keywords:
  - "FIRST SCHEDULE", "SECOND SCHEDULE", "THIRD SCHEDULE", or just "SCHEDULE"
  - "PART I", "PART II", "PART III" (when in schedule context)
  - "FEES", "TARIFFS" (indicators of fee schedules)

  IF ANY FOUND → This is a SCHEDULE page:
    - Set page_content_type to "schedule_text" (for lists) or "schedule_table" (for tables)
    - Check for "REGULATION X" headers inside schedule → extract to "schedule_regulations"
    - CRITICAL: Set {item_type_plural} = [] (do NOT extract {item_type_plural} from schedule pages)

STEP 2: Scan for FORM keywords:
  - "Form 1", "Form 2", "Form A", "Form B", "Form BB", etc.

  IF FOUND + page has blank fields (_____, □, signature lines):
    - Set page_content_type to "form"
    - Set {item_type_plural} = [] and schedule_content = []
    - STOP HERE - Do not extract content from blank forms

STEP 3: Default classification - {item_type_upper}S page:
  IF no schedule or form keywords found:
    - Set page_content_type to "{item_type_plural}"
    - Extract bold numbered items (1., 2., 23A., etc.) into {item_type_plural} array
    - Set schedule_content = []

</classification_instructions>

=== STEP 2: EXTRACT {item_type_upper}S ===

CRITICAL: When extracting {item_type_plural}, capture the COMPLETE text including ALL sub-{item_type}s in ONE entry.

For each main {item_type} (bold number with period):
1. Extract the ENTIRE text including all (1), (2), (a), (b), (i), (ii) sub-{item_type}s
2. List all sub-{item_type} numbers in "sub_items" array
3. This keeps the {item_type} as ONE coherent chunk for RAG

**CRITICAL - HIERARCHICAL NUMBERING:**
When you encounter letter sub-items (a), (b), (c), you MUST track which numbered section they belong to:

Step-by-step process:
1. Track your current numbered section as you read: (1), (2), (3), etc.
2. When you see a letter (a), (b), (c) - it belongs to the MOST RECENT numbered section
3. Format as: {{main}}({{numbered_section}})({{letter}})

Example hierarchy:
```
4. Board Composition
   (1) The board shall consist...        → sub_item: "4(1)"
   (2) Members shall include:            → sub_item: "4(2)"
       (a) a chairperson                 → sub_item: "4(2)(a)" ✅ (belongs to section 2)
       (b) a deputy                      → sub_item: "4(2)(b)" ✅ (belongs to section 2)
   (3) Disqualifications:                → sub_item: "4(3)"
       (a) convicted persons             → sub_item: "4(3)(a)" ✅ (belongs to section 3)
       (b) interdicted persons           → sub_item: "4(3)(b)" ✅ (belongs to section 3)
       (c) judges                        → sub_item: "4(3)(c)" ✅ (belongs to section 3)
```

❌ WRONG: ["4(1)", "4(2)", "4(a)", "4(b)", "4(3)", "4(a)", "4(b)"]
✅ CORRECT: ["4(1)", "4(2)", "4(2)(a)", "4(2)(b)", "4(3)", "4(3)(a)", "4(3)(b)", "4(3)(c)"]

Complete Example:
{{
  "number": "4",
  "title": "Board Composition",
  "text": "(1) The board shall consist...\\n(2) Members shall include:\\n(a) a chairperson\\n(b) a deputy\\n(3) Disqualifications:\\n(a) convicted persons\\n(b) interdicted persons...",
  "sub_items": ["4(1)", "4(2)", "4(2)(a)", "4(2)(b)", "4(3)", "4(3)(a)", "4(3)(b)", "4(3)(c)"],
  "continues_from_previous": false,
  "continues_to_next": false
}}

=== STEP 3: EXTRACT CROSS-REFERENCES ===

INTERNAL references (within same law):
- "{item_type} 28B" or "{item_type} 5(2)" or "{item_type}s 86 to 90"
- Set scope: "internal", target_law: null

EXTERNAL references (to other laws):
- Any reference mentioning a SPECIFIC ACT NAME with "Cap. XX" or "S.L. XXX.XX"
- Set scope: "external", target_law: "Cap. 9" or "S.L. 146.02"

**CRITICAL - REFERENCE VALIDATION:**
DO NOT extract these as references (they are too generic or self-referential):
❌ "this order" / "this regulation" / "this act" (self-references)
❌ "the Constitution" (unless you have a Cap. number)
❌ "the Act" (too generic - which act?)
❌ "any law relating to..." (not a specific law)
❌ Generic phrases without specific law codes

✅ ONLY extract references with:
- Specific Cap. numbers: "Cap. 9", "Cap. 386"
- Specific S.L. numbers: "S.L. 146.02"
- Named acts WITH Cap. numbers: "Companies Act (Cap. 386)"
- Specific article numbers: "article 28", "regulation 5(2)"

When you see "the Constitution", use "the Constitution" as target_law ONLY if there's an article number.
If no article number, skip it.

=== OUTPUT FORMAT ===

{{
    "page_content_type": "{item_type_plural}|schedule_text|schedule_table|schedule_regulations|form|form_template|skip",
    "skip_reason": null | "title_page" | "toc" | "blank",
    "schedule_name": null | "FIRST SCHEDULE" | "SCHEDULE",

    "{item_type_plural}": [
        {{
            "number": "5",
            "title": "Penalties",
            "text": "(1) Every person who commits...\\n(2) The court may impose:\\n(a) a fine not exceeding...\\n(b) imprisonment...",
            "sub_items": ["5(1)", "5(2)", "5(2)(a)", "5(2)(b)"],
            "continues_from_previous": false,
            "continues_to_next": false
        }}
    ],

    "schedule_content": [
        {{"number": "1", "title": "Fee item", "text": "For filing... €50.00", "continues_from_previous": false, "continues_to_next": false}}
    ],

    "schedule_regulations": [
        {{"regulation_number": "1", "title": "APPLICABILITY", "text": "Full regulation text..."}}
    ],

    "cross_references": [
        {{"type": "{item_type}", "target": "5(2)", "found_in_{item_type}": "10", "target_law": null, "scope": "internal"}},
        {{"type": "{item_type}", "target": "article 28", "found_in_{item_type}": "10", "target_law": "Cap. 9", "scope": "external"}}
    ],

    "last_{item_type}_on_page": "6",
    "last_{item_type}_ended": true,
    "last_schedule_section": null,
    "last_schedule_ended": true,
    "last_form_number": null,
    "last_form_ended": true
}}

=== CRITICAL REQUIREMENTS ===

1. ALWAYS return valid JSON - NEVER return empty or plain text
2. Keep each {item_type} as ONE chunk with complete text (don't split sub-{item_type}s)
3. NEVER extract schedule sections as {item_type_plural}
4. If page has no extractable content, use page_content_type: "skip"
5. Track last_{item_type}_on_page for continuation to next page

Return ONLY valid JSON. No other text."""


def build_table_description_prompt(law_name: str, table_context: str) -> str:
    """Build prompt for generating AI description of a table"""
    return f"""You are analyzing a table from {law_name}.

Table context: {table_context}

Generate a clear, natural description of this table that would help someone searching for this information. Include:
- What the table contains
- Key data types/columns
- Purpose (fees, exemptions, lists, etc.)
- Any referenced articles or regulations

Keep the description concise (2-3 sentences) but informative for search purposes.

Return ONLY the description text, no JSON or formatting."""


def build_metadata_prompt(law_name: str, cap: str, sample_text: str, is_subsidiary: bool = False, parent_summary: Optional[str] = None) -> str:
    """Build prompt for generating law metadata.
    Matches format used by multi_model_extraction.py for consistency.
    """
    # Context for subsidiary legislation
    if is_subsidiary and parent_summary:
        context = f"""
=== PARENT LAW CONTEXT ===
This is SUBSIDIARY LEGISLATION under a parent law.
Parent Law Summary: {parent_summary}

The subsidiary legislation provides specific regulations, rules, or procedures
that implement or support the parent law.
"""
    elif is_subsidiary:
        context = """
=== SUBSIDIARY LEGISLATION ===
This is subsidiary legislation (S.L.) - detailed regulations implementing a parent law.
"""
    else:
        context = """
=== PARENT LAW ===
This is a PRIMARY/PARENT LAW (Chapter or Act).
"""

    return f"""You are summarizing Maltese legislation for a legal RAG system.

{context}

=== DOCUMENT ===
Code: {cap}
Name: {law_name}

Sample content:
{sample_text[:3000]}

=== TASK ===
Create a summary optimized for legal search/retrieval:

1. **Purpose** (1-2 sentences): What is this law about? What does it regulate?

2. **Key Topics** (bullet points): List 5-10 specific topics/subjects this law covers.
   - Be specific: "licensing requirements for food establishments" not just "licensing"
   - Include legal terms that lawyers might search for

3. **Scope** (1 sentence): Who/what does this law apply to?

4. **Categories** (list): Select 1-4 categories from this list (use snake_case):
   - criminal_law (crimes, offenses, punishments)
   - civil_law (contracts, property, family, torts)
   - commercial_law (business, companies, trade)
   - administrative_law (government, public administration)
   - constitutional_law (constitution, rights, government structure)
   - labour_law (employment, workers rights)
   - tax_law (taxation, revenue)
   - environmental_law (environment, conservation)
   - immigration_law (immigration, citizenship)
   - maritime_law (shipping, maritime affairs)
   - financial_services_law (banking, finance, insurance)
   - health_law (health, medicine, pharmaceuticals)
   - property_law (real estate, land, ownership)
   - procedural_law (court procedures, evidence)
   - international_law (treaties, international relations)
   - transport_law (traffic, vehicles, transportation)
   - planning_and_development_law (zoning, construction, development)
   - consumer_protection_law (consumer rights, product safety)
   - police_and_law_enforcement_law (police powers, public order)
   - eu_law (European Union related)
   - other (if none of the above fit)

{"5. **Relation to Parent** (1-2 sentences): How does this S.L. implement or support the parent law?" if is_subsidiary else ""}

6. **Summary Text** (1-2 sentences): A concise summary for search purposes.

Return JSON only:
{{
    "purpose": "...",
    "key_topics": ["topic1", "topic2", ...],
    "scope": "...",
    "categories": ["criminal_law", "administrative_law"],
    {"\"relation_to_parent\": \"...\"," if is_subsidiary else ""}
    "summary_text": "..."
}}

Return ONLY valid JSON."""


def generate_law_metadata(
    model: GenerativeModel,
    law_name: str,
    cap: str,
    sample_items: List[Dict],
    parent_summary: Optional[str] = None
) -> Optional[LawMetadata]:
    """Generate metadata for a law using AI.

    Args:
        model: The Gemini model to use
        law_name: Name of the law
        cap: Law code (Cap. X or S.L. X.XX)
        sample_items: Sample of extracted articles/regulations for context
        parent_summary: Summary of parent law (for S.L. laws)

    Returns:
        LawMetadata object or None on failure
    """
    is_subsidiary = is_subsidiary_legislation(cap)

    # Build sample text from first few items
    sample_texts = []
    for item in sample_items[:5]:
        if item.get("text"):
            sample_texts.append(f"{item.get('number', 'N/A')}: {item['text'][:500]}")

    sample_text = "\n\n".join(sample_texts) if sample_texts else f"Law: {law_name}"

    prompt = build_metadata_prompt(law_name, cap, sample_text, is_subsidiary, parent_summary)

    try:
        response = generate_content_with_timeout(
            model,
            prompt,
            safety_settings=SAFETY_SETTINGS,
            generation_config={"temperature": 0.3}
        )

        if response.candidates and response.candidates[0].content:
            raw_text = response.candidates[0].content.parts[0].text.strip()

            # Clean up response
            if raw_text.startswith("```"):
                raw_text = re.sub(r'^```json?\n?', '', raw_text)
                raw_text = re.sub(r'\n?```$', '', raw_text)

            parsed = json.loads(raw_text)

            return LawMetadata(
                purpose=parsed.get("purpose", ""),
                key_topics=parsed.get("key_topics", []),
                scope=parsed.get("scope", ""),
                categories=parsed.get("categories", ["other"]),
                summary_text=parsed.get("summary_text", ""),
                relation_to_parent=parsed.get("relation_to_parent") if is_subsidiary else None,
                status="success"
            )

    except FunctionTimedOut:
        print(f"  Warning: Metadata generation timed out after {API_TIMEOUT}s")
    except Exception as e:
        print(f"  Warning: Could not generate metadata: {e}")

    return None


# =============================================================================
# EXTRACTION FUNCTIONS
# =============================================================================

def extract_page(
    model: GenerativeModel,
    page: fitz.Page,
    page_num: int,
    cap: str,
    law_name: str,
    prev_item_number: Optional[str] = None,
    prev_item_ended: bool = True,
    prev_schedule_section: Optional[str] = None,
    prev_schedule_ended: bool = True,
    prev_form_number: Optional[str] = None,
    prev_form_ended: bool = True
) -> Tuple[Optional[Dict], str]:
    """Extract content from a single page

    Returns:
        Tuple of (parsed_response, raw_response)
        Returns (None, error_message) on failure
    """
    is_subsidiary = is_subsidiary_legislation(cap)

    # Build prompt
    prompt = build_extraction_prompt(
        cap=cap,
        law_name=law_name,
        is_subsidiary=is_subsidiary,
        prev_item_number=prev_item_number,
        prev_item_ended=prev_item_ended,
        prev_schedule_section=prev_schedule_section,
        prev_schedule_ended=prev_schedule_ended,
        prev_form_number=prev_form_number,
        prev_form_ended=prev_form_ended
    )

    # Convert page to image
    img_base64 = page_to_image_base64(page)
    image_part = Part.from_data(base64.b64decode(img_base64), mime_type="image/png")

    # Call model
    try:
        response = generate_content_with_timeout(
            model,
            [prompt, image_part],
            safety_settings=SAFETY_SETTINGS,
            generation_config={"temperature": 0}
        )

        # Check for blocked response
        if not response.candidates:
            return None, "NO_CANDIDATES"

        candidate = response.candidates[0]
        if candidate.finish_reason.name == "SAFETY":
            return None, "SAFETY_BLOCKED"

        if not candidate.content or not candidate.content.parts:
            return None, "EMPTY_RESPONSE"

        raw_text = candidate.content.parts[0].text.strip()

        # Parse JSON
        # Clean up response (remove markdown if present)
        if raw_text.startswith("```"):
            raw_text = re.sub(r'^```json?\n?', '', raw_text)
            raw_text = re.sub(r'\n?```$', '', raw_text)

        parsed = json.loads(raw_text)
        return parsed, raw_text

    except FunctionTimedOut as e:
        print(f"\n  Timeout after {API_TIMEOUT}s")
        return None, "TIMEOUT"
    except json.JSONDecodeError as e:
        # Print the raw text that failed to parse for debugging
        print(f"\n  JSON Parse Error: {str(e)[:100]}")
        return None, f"JSON_PARSE_ERROR: {str(e)[:50]}"
    except Exception as e:
        error_msg = str(e)
        # Catch any timeout-related errors (including func_timeout threading issues)
        if "timeout" in error_msg.lower() or "timed out" in error_msg.lower() or "deadline" in error_msg.lower():
            print(f"\n  Timeout detected in exception")
            return None, "TIMEOUT"
        print(f"\n  Exception: {error_msg[:100]}")
        return None, f"ERROR: {error_msg[:50]}"


def extract_with_fallback(
    models: Dict[str, GenerativeModel],
    page: fitz.Page,
    page_num: int,
    cap: str,
    law_name: str,
    **kwargs
) -> Tuple[Optional[Dict], str, str]:
    """Try extraction with fallback models

    Returns:
        Tuple of (parsed_response, raw_response, model_used)
    """
    model_order = ["primary", "fallback_1", "fallback_2"]

    for model_key in model_order:
        if model_key not in models:
            continue

        model = models[model_key]

        for attempt in range(MAX_RETRIES):
            result, raw = extract_page(
                model=model,
                page=page,
                page_num=page_num,
                cap=cap,
                law_name=law_name,
                **kwargs
            )

            if result is not None:
                return result, raw, MODELS[model_key]

            # Skip instantly on certain errors (no retries)
            if raw in ["EMPTY_RESPONSE", "SAFETY_BLOCKED", "NO_CANDIDATES", "TIMEOUT"]:
                print(f"  [Page {page_num + 1}] {raw} - skipping instantly")
                return None, raw, MODELS[model_key]

            # For other errors, try once more then move to next model
            if attempt < MAX_RETRIES - 1:
                print(f"  [Page {page_num + 1}] Retry {attempt + 1}/{MAX_RETRIES}...")
                time.sleep(RETRY_DELAY)
            else:
                print(f"  [Page {page_num + 1}] Failed with {MODELS[model_key]}, trying next model...")
                break

    # All models failed
    return None, "ALL_MODELS_FAILED", "none"


def generate_table_description(
    model: GenerativeModel,
    page: fitz.Page,
    law_name: str,
    table_context: str
) -> str:
    """Generate AI description for a table"""
    prompt = build_table_description_prompt(law_name, table_context)
    img_base64 = page_to_image_base64(page)
    image_part = Part.from_data(base64.b64decode(img_base64), mime_type="image/png")

    try:
        response = generate_content_with_timeout(
            model,
            [prompt, image_part],
            safety_settings=SAFETY_SETTINGS,
            generation_config={"temperature": 0.3}
        )

        if response.candidates and response.candidates[0].content:
            return response.candidates[0].content.parts[0].text.strip()
    except FunctionTimedOut:
        print(f"  Warning: Table description generation timed out after {API_TIMEOUT}s")
    except Exception as e:
        print(f"  Warning: Could not generate table description: {e}")

    return "Table content (description unavailable)"


def extract_fallback_text(
    model: GenerativeModel,
    page: fitz.Page,
    page_num: int,
    cap: str,
    law_name: str
) -> Optional[Dict]:
    """Fallback extraction - just get raw text from the page when structured extraction fails.

    Returns a miscellaneous chunk with the raw page text.
    """
    prompt = f"""You are extracting text from page {page_num + 1} of {law_name} ({cap}).

The structured extraction failed, so just extract ALL visible text from this page.

Return a simple JSON:
{{
    "page_text": "All the text visible on this page, preserving structure as much as possible...",
    "has_content": true
}}

If the page is blank or has no meaningful text, return:
{{
    "page_text": "",
    "has_content": false
}}

Return ONLY valid JSON."""

    img_base64 = page_to_image_base64(page)
    image_part = Part.from_data(base64.b64decode(img_base64), mime_type="image/png")

    try:
        response = generate_content_with_timeout(
            model,
            [prompt, image_part],
            safety_settings=SAFETY_SETTINGS,
            generation_config={"temperature": 0}
        )

        if response.candidates and response.candidates[0].content:
            raw_text = response.candidates[0].content.parts[0].text.strip()

            # Clean up response
            if raw_text.startswith("```"):
                raw_text = re.sub(r'^```json?\n?', '', raw_text)
                raw_text = re.sub(r'\n?```$', '', raw_text)

            parsed = json.loads(raw_text)

            if parsed.get("has_content") and parsed.get("page_text"):
                return {
                    "id": f"misc:{normalize_code(cap)}/page/{page_num + 1}",
                    "type": "miscellaneous",
                    "text": parsed["page_text"],
                    "page": page_num + 1,
                    "extraction_method": "fallback_ocr"
                }

    except FunctionTimedOut:
        print(f"  Fallback extraction timed out after {API_TIMEOUT}s")
    except Exception as e:
        print(f"  Fallback extraction also failed: {e}")

    return None


# =============================================================================
# MAIN PROCESSING
# =============================================================================

def process_law(
    pdf_path: str,
    cap: str,
    law_name: str,
    page_range: Optional[range] = None
) -> LawExtraction:
    """Process a complete law PDF and extract all content"""

    print(f"\n{'='*60}")
    print(f"Processing: {law_name} ({cap})")
    print(f"PDF: {pdf_path}")
    print(f"{'='*60}\n")

    # Determine law type
    is_subsidiary = is_subsidiary_legislation(cap)
    law_type = "subsidiary" if is_subsidiary else "chapter"
    content_key = get_content_type_name(cap)  # "articles" or "regulations"
    item_type = get_item_type(cap)  # "article" or "regulation"

    print(f"Law type: {law_type.upper()}")
    print(f"Content type: {content_key.upper()}")
    print()

    # Validate and Initialize Vertex AI
    if not PROJECT_ID:
        raise ValueError("GOOGLE_CLOUD_PROJECT not set in .env file")

    creds_path = os.environ.get('GOOGLE_APPLICATION_CREDENTIALS', '')
    if not creds_path or not Path(creds_path).exists():
        raise ValueError(f"Credentials file not found: {creds_path}")

    print(f"Project: {PROJECT_ID}")
    print(f"Location: {LOCATION}")
    print(f"Credentials: {Path(creds_path).name}")

    vertexai.init(project=PROJECT_ID, location=LOCATION)

    # Load models
    models = {}
    for key, model_name in MODELS.items():
        try:
            models[key] = GenerativeModel(model_name)
            print(f"Loaded model: {model_name}")
        except Exception as e:
            print(f"Warning: Could not load {model_name}: {e}")

    if not models:
        raise RuntimeError("No models available!")

    # Open PDF
    doc = fitz.open(pdf_path)
    total_pages = len(doc)

    # Determine pages to process
    if page_range is None:
        pages_to_process = range(total_pages)
    else:
        pages_to_process = page_range

    print(f"\nTotal pages in PDF: {total_pages}")
    print(f"Processing pages: {pages_to_process.start + 1} to {pages_to_process.stop}")
    print()

    # Track state
    all_items = {}  # Dict to merge items by main number
    all_schedules = {}  # Dict to merge schedules by ID
    all_miscellaneous = []  # Fallback extracted content
    all_edges = []
    skipped = []

    # Page-to-page state tracking
    prev_item_number = None
    prev_item_ended = True
    prev_schedule_section = None
    prev_schedule_ended = True
    prev_form_number = None
    prev_form_ended = True

    start_time = time.time()

    # Process each page
    for page_idx in pages_to_process:
        if page_idx >= total_pages:
            break

        page = doc[page_idx]
        print(f"[Page {page_idx + 1}/{total_pages}] Processing...", end=" ", flush=True)

        # Extract page
        result, raw, model_used = extract_with_fallback(
            models=models,
            page=page,
            page_num=page_idx,
            cap=cap,
            law_name=law_name,
            prev_item_number=prev_item_number,
            prev_item_ended=prev_item_ended,
            prev_schedule_section=prev_schedule_section,
            prev_schedule_ended=prev_schedule_ended,
            prev_form_number=prev_form_number,
            prev_form_ended=prev_form_ended
        )

        if result is None:
            # Try fallback extraction
            print(f"structured failed ({raw}), trying fallback...", end=" ", flush=True)
            fallback_result = None
            if "primary" in models:
                fallback_result = extract_fallback_text(
                    models["primary"],
                    page,
                    page_idx,
                    cap,
                    law_name
                )

            if fallback_result:
                all_miscellaneous.append(fallback_result)
                print(f"MISC (fallback OK)")
            else:
                print(f"SKIPPED (all failed)")
                skipped.append({
                    "page": page_idx + 1,
                    "reason": raw,
                    "model_attempted": model_used
                })
            continue

        # Handle skip pages
        page_content_type = result.get("page_content_type", "")
        if page_content_type == "skip":
            skip_reason = result.get("skip_reason", "unknown")
            print(f"SKIP ({skip_reason})")
            skipped.append({
                "page": page_idx + 1,
                "reason": skip_reason,
                "model_used": model_used
            })
            continue

        # Handle form pages (skip but track)
        if page_content_type in ["form", "form_template"]:
            form_num = result.get("last_form_number", "unknown")
            print(f"FORM ({form_num})")
            skipped.append({
                "page": page_idx + 1,
                "reason": f"form:{form_num}",
                "model_used": model_used
            })
            # Update form state
            prev_form_number = result.get("last_form_number")
            prev_form_ended = result.get("last_form_ended", True)
            continue

        # Process items (articles/regulations) - use dynamic key
        items = result.get(content_key, []) or result.get("articles", []) or result.get("regulations", [])
        items_found = 0

        for item in items:
            item_num = item.get("number", "")
            if not item_num:
                continue

            main_num = extract_main_number(item_num)
            item_id = generate_item_id(cap, main_num)

            # Check if this item continues from previous page
            if item.get("continues_from_previous") and main_num in all_items:
                # Append text to existing item
                existing = all_items[main_num]
                # Handle None text values
                existing_text = existing["text"] or ""
                new_text = item.get("text") or ""
                existing["text"] = existing_text + "\n" + new_text
                existing["page_end"] = page_idx + 1
                # Merge sub-items
                existing_subs = set(existing.get("sub_items", []))
                new_subs = set(item.get("sub_items", []))
                existing["sub_items"] = sorted(list(existing_subs | new_subs))
            else:
                # New item
                all_items[main_num] = {
                    "id": item_id,
                    "type": item_type,
                    "number": main_num,
                    "title": item.get("title") or "",
                    "text": item.get("text") or "",
                    "sub_items": item.get("sub_items", []),
                    "page_start": page_idx + 1,
                    "page_end": page_idx + 1,
                    "cross_references": {
                        "internal": [],
                        "external": []
                    }
                }
                items_found += 1

        # Process cross-references
        cross_refs = result.get("cross_references", [])
        for ref in cross_refs:
            # Get source item number (try multiple field names)
            source_num = ref.get(f"found_in_{item_type}", "") or ref.get("source_item", "") or ref.get("found_in_article", "") or ref.get("found_in_regulation", "")
            source_main = extract_main_number(source_num) if source_num else None

            if not source_main or source_main not in all_items:
                continue

            scope = ref.get("scope", "internal")
            target = ref.get("target", "")
            target_law = ref.get("target_law")

            if scope == "internal" and target:
                # Expand ranges like "311 to 318" into individual references
                expanded_targets = expand_reference_range(target)

                for single_target in expanded_targets:
                    target_main = extract_main_number(single_target)
                    target_id = generate_item_id(cap, target_main)

                    # Check if we have a sub-reference (e.g., "5(1)")
                    cleaned_target = clean_reference_target(single_target)
                    has_sub = cleaned_target != target_main

                    all_items[source_main]["cross_references"]["internal"].append({
                        "target": target_main,  # Clean number only
                        "target_id": target_id,
                        "sub_target": cleaned_target if has_sub else None
                    })

                    # Create edge for each expanded target
                    all_edges.append({
                        "source_id": all_items[source_main]["id"],
                        "target_id": target_id,
                        "type": "INTERNAL_REF",
                        "sub_target": cleaned_target if has_sub else None
                    })

            elif scope == "external" and target_law:
                # Use parse_external_reference for proper ID structure
                ext_ref = parse_external_reference(target, target_law)
                target_id = ext_ref["target_id"]

                if target_id:
                    all_items[source_main]["cross_references"]["external"].append({
                        "target": clean_reference_target(target) if target else None,
                        "target_law": target_law,
                        "target_id": target_id,
                        "has_article": ext_ref["has_article"]
                    })

                    # Create edge
                    all_edges.append({
                        "source_id": all_items[source_main]["id"],
                        "target_id": target_id,
                        "type": "EXTERNAL_REF",
                        "target_law": target_law
                    })

        # Process schedule content
        schedule_content = result.get("schedule_content", [])
        schedule_name = result.get("schedule_name") or "Schedule"  # Handle None explicitly
        schedules_found = 0

        if schedule_content or page_content_type in ["schedule_text", "schedule_table"]:
            sched_id = generate_schedule_id(cap, schedule_name)

            # Check if schedule already exists (continuation)
            if sched_id in all_schedules:
                existing_sched = all_schedules[sched_id]
                # Append content
                for section in schedule_content:
                    existing_sched["sections"].append(section)
                existing_sched["page_end"] = page_idx + 1
            else:
                # New schedule
                content_type = "fee_table" if page_content_type == "schedule_table" else "text"

                # Generate AI description for tables
                ai_description = None
                if content_type == "fee_table" and "primary" in models:
                    ai_description = generate_table_description(
                        models["primary"],
                        page,
                        law_name,
                        f"Schedule: {schedule_name}"
                    )

                all_schedules[sched_id] = {
                    "id": sched_id,
                    "type": "schedule",
                    "name": schedule_name,
                    "content_type": content_type,
                    "sections": schedule_content,
                    "ai_description": ai_description,
                    "page_start": page_idx + 1,
                    "page_end": page_idx + 1
                }
                schedules_found = 1

        # Process schedule regulations (REGULATION 1, 2, 3 inside schedules)
        schedule_regs = result.get("schedule_regulations", [])
        for sched_reg in schedule_regs:
            reg_num = sched_reg.get("regulation_number", "")
            sched_id = generate_schedule_id(cap, schedule_name, reg_num)

            if sched_id in all_schedules:
                # Continuation
                existing = all_schedules[sched_id]
                existing["text"] += "\n" + sched_reg.get("text", "")
                existing["page_end"] = page_idx + 1
            else:
                all_schedules[sched_id] = {
                    "id": sched_id,
                    "type": "schedule_regulation",
                    "schedule_name": schedule_name,
                    "regulation_number": reg_num,
                    "title": sched_reg.get("title", ""),
                    "text": sched_reg.get("text", ""),
                    "page_start": page_idx + 1,
                    "page_end": page_idx + 1
                }
                schedules_found += 1

        # Update state for next page (use dynamic field names)
        prev_item_number = result.get(f"last_{item_type}_on_page") or result.get("last_article_on_page") or result.get("last_regulation_on_page")
        prev_item_ended = result.get(f"last_{item_type}_ended", result.get("last_article_ended", result.get("last_regulation_ended", True)))
        prev_schedule_section = result.get("last_schedule_section")
        prev_schedule_ended = result.get("last_schedule_ended", True)
        prev_form_number = result.get("last_form_number")
        prev_form_ended = result.get("last_form_ended", True)

        # Print summary
        print(f"OK - {items_found} {content_key}, {schedules_found} schedules")

    doc.close()

    # Calculate metrics
    end_time = time.time()
    elapsed = end_time - start_time

    metrics = {
        "total_pages_in_pdf": total_pages,
        "pages_processed": len(pages_to_process),
        "pages_skipped": len(skipped),
        f"{content_key}_extracted": len(all_items),
        "schedules_extracted": len(all_schedules),
        "miscellaneous_extracted": len(all_miscellaneous),
        "edges_created": len(all_edges),
        "extraction_time_seconds": round(elapsed, 2),
        "extraction_timestamp": datetime.now().isoformat()
    }

    # Load/generate law metadata using cache (shared with multi_model_extraction)
    print("\nLoading law metadata...", end=" ", flush=True)
    metadata = None
    summaries_cache = load_summaries_cache()

    # Check if already cached
    if cap in summaries_cache:
        cached = summaries_cache[cap].get("summary", {})
        if cached.get("status") == "success":
            print(f"CACHED - Categories: {', '.join(cached.get('categories', []))}")
            metadata = LawMetadata(
                purpose=cached.get("purpose", ""),
                key_topics=cached.get("key_topics", []),
                scope=cached.get("scope", ""),
                categories=cached.get("categories", ["other"]),
                summary_text=cached.get("summary_text", ""),
                relation_to_parent=cached.get("relation_to_parent"),
                status="success"
            )

    # Not cached - generate new metadata
    if metadata is None and "primary" in models and all_items:
        print("generating...", end=" ", flush=True)

        # Get parent summary if this is subsidiary legislation
        parent_summary = None
        parent_code = get_parent_code(cap)
        if parent_code and parent_code in summaries_cache:
            parent_data = summaries_cache[parent_code].get("summary", {})
            if parent_data.get("status") == "success":
                parent_summary = parent_data.get("summary_text", "")
                print(f"(using parent {parent_code})...", end=" ", flush=True)

        metadata = generate_law_metadata(
            models["primary"],
            law_name,
            cap,
            list(all_items.values()),
            parent_summary
        )

        if metadata:
            print(f"OK - Categories: {', '.join(metadata.categories)}")
            # Cache this summary
            summaries_cache[cap] = {
                "code": cap,
                "name": law_name,
                "type": "subsidiary" if is_subsidiary else "parent",
                "parent_code": parent_code if is_subsidiary else None,
                "pdf_path": pdf_path,
                "summary": {
                    "purpose": metadata.purpose,
                    "key_topics": metadata.key_topics,
                    "scope": metadata.scope,
                    "categories": metadata.categories,
                    "relation_to_parent": metadata.relation_to_parent,
                    "summary_text": metadata.summary_text,
                    "status": "success"
                }
            }
            save_summaries_cache(summaries_cache)
            print(f"  Saved to cache: {SUMMARIES_CACHE_PATH}")
        else:
            print("FAILED (generation error)")
    elif metadata is None:
        print("SKIPPED (no items or models available)")

    # Build result
    return LawExtraction(
        law_code=cap,
        law_name=law_name,
        law_type=law_type,
        content_key=content_key,
        metadata=metadata,
        items=list(all_items.values()),
        schedules=list(all_schedules.values()),
        miscellaneous=all_miscellaneous,
        skipped=skipped,
        metrics=metrics,
        edges=all_edges
    )


def save_extraction(extraction: LawExtraction, output_dir: str = ".") -> str:
    """Save extraction result to JSON file"""

    # Build metadata dict if available (matches law_summaries.json structure)
    metadata_dict = None
    if extraction.metadata:
        metadata_dict = {
            "purpose": extraction.metadata.purpose,
            "key_topics": extraction.metadata.key_topics,
            "scope": extraction.metadata.scope,
            "categories": extraction.metadata.categories,
            "summary_text": extraction.metadata.summary_text,
            "relation_to_parent": extraction.metadata.relation_to_parent,
            "status": extraction.metadata.status
        }

    # Build output structure - metadata at the top for visibility
    output = {
        "law_code": extraction.law_code,
        "law_name": extraction.law_name,
        "law_type": extraction.law_type,
        "metadata": metadata_dict,
        extraction.content_key: extraction.items,
        "schedules": extraction.schedules,
        "miscellaneous": extraction.miscellaneous,
        "edges": extraction.edges,
        "skipped": extraction.skipped,
        "metrics": extraction.metrics
    }

    # Generate filename
    code_clean = normalize_code(extraction.law_code)
    filename = f"extraction_{code_clean}.json"
    filepath = os.path.join(output_dir, filename)

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(output, f, indent=2, ensure_ascii=False)

    print(f"\nSaved extraction to: {filepath}")
    return filepath


# =============================================================================
# INTERRUPT HANDLER
# =============================================================================

def handle_interrupt(signum, frame):
    """Handle Ctrl+C gracefully - save progress before exiting"""
    global _extraction_in_progress, _all_completed_extractions

    print("\n\n" + "="*60)
    print("INTERRUPT DETECTED - SAVING PROGRESS")
    print("="*60)

    # Save the current extraction if it was in progress
    if _extraction_in_progress is not None:
        print(f"\nSaving in-progress extraction: {_extraction_in_progress.law_code}")
        try:
            save_extraction(_extraction_in_progress, OUTPUT_DIR)
            print(f"[OK] Saved in-progress extraction")
        except Exception as e:
            print(f"[ERROR] Failed to save in-progress extraction: {e}")

    # Print summary of completed extractions
    print(f"\nCompleted extractions before interrupt: {len(_all_completed_extractions)}")
    for ext in _all_completed_extractions:
        items_count = ext.metrics.get(f"{ext.content_key}_extracted", 0)
        print(f"  - {ext.law_code}: {items_count} {ext.content_key}, {ext.metrics.get('edges_created', 0)} edges")

    print("\n[OK] Progress saved. You can resume extraction by running the script again.")
    print("Already extracted laws will be skipped if their JSON files exist.\n")
    sys.exit(0)


# =============================================================================
# MAIN
# =============================================================================

def main():
    """Main entry point - processes all laws in LAWS_TO_EXTRACT"""
    global _extraction_in_progress, _all_completed_extractions

    # Register interrupt handler for graceful shutdown
    signal.signal(signal.SIGINT, handle_interrupt)

    # Create output directory if it doesn't exist
    Path(OUTPUT_DIR).mkdir(exist_ok=True)
    print(f"Output directory: {OUTPUT_DIR}/")

    print("\n" + "="*60)
    print("GRAPH RAG EXTRACTION FOR MALTA LAWS")
    print("="*60)
    print(f"\nLaws to extract: {len(LAWS_TO_EXTRACT)}")
    for i, law in enumerate(LAWS_TO_EXTRACT, 1):
        print(f"  {i}. {law['name']} ({law['cap']})")

    all_extractions = []

    for i, law_config in enumerate(LAWS_TO_EXTRACT, 1):
        print("\n" + "="*60)
        print(f"EXTRACTING LAW {i}/{len(LAWS_TO_EXTRACT)}: {law_config['name']}")
        print("="*60)

        # Check if this law was already extracted (resume capability)
        code_clean = normalize_code(law_config["cap"])
        output_file = Path(OUTPUT_DIR) / f"extraction_{code_clean}.json"
        if output_file.exists():
            print(f"[SKIP] Already extracted - file exists: {output_file}")
            continue

        # Process this law
        extraction = process_law(
            pdf_path=law_config["pdf_path"],
            cap=law_config["cap"],
            law_name=law_config["name"],
            page_range=law_config.get("page_range")
        )

        # Track in-progress extraction (for interrupt handler)
        _extraction_in_progress = extraction

        # Print summary for this law
        print("\n" + "-"*40)
        print(f"SUMMARY: {extraction.law_name} ({extraction.law_code})")
        print("-"*40)
        print(f"Type: {extraction.law_type}")
        print(f"Metrics:")
        for key, value in extraction.metrics.items():
            print(f"  {key}: {value}")

        # Save this extraction to its own JSON file in the output directory
        save_extraction(extraction, OUTPUT_DIR)
        all_extractions.append(extraction)

        # Track completed extractions (for interrupt handler)
        _all_completed_extractions.append(extraction)
        _extraction_in_progress = None  # Clear in-progress tracker

    # Final summary
    print("\n" + "="*60)
    print("ALL EXTRACTIONS COMPLETE")
    print("="*60)
    print(f"Total laws extracted: {len(all_extractions)}")
    for ext in all_extractions:
        items_count = ext.metrics.get(f"{ext.content_key}_extracted", 0)
        print(f"  - {ext.law_code}: {items_count} {ext.content_key}, {ext.metrics.get('edges_created', 0)} edges")

    print("\nDone!")


if __name__ == "__main__":
    main()
